<?php

/**
 * PLEASE DO NOT EDIT THIS FILE DIRECTLY!
 * You can change the following settings by coping this file to `app/config/production` and then edit that file
 */
return [
    'top_level' => 'email',             // Use `views/email.phtml` as top level html
    'layout'    => 'phwoolcon-default', // Use `views/email/layouts/phwoolcon-default.phtml` as layout
    'dir'       => 'email',             // Use `views/email/` as template dir
];
