<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<!DOCTYPE html>
<html lang="<?= View::getPageLanguage(); ?>">
<head>
    <title><?= View::getParam('subject') ?></title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <meta name="viewport" content="width=320, target-densitydpi=device-dpi"/>
    <?php MailRenderer::renderCss() ?>
    <!--[if gte mso 9]>
    <style _tmplitem="1681">.article-content ol, .article-content ul{margin:0 0 0 24px;padding:0;list-style-position:inside;}</style>
    <![endif]-->
</head>
<body>
<?= $this->getContent(); ?>
</body>
</html>
