<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<table cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td style="font-size:14px;line-height:2em;text-align:right;white-space:nowrap;" width="50">
            <?= __('Customer Service Call:'); ?>
        </td>
        <td style="font-size:14px;line-height:2em;">
            <a href="tel:400x-xxx-xxx">400x-xxx-xxx</a>
        </td>
    </tr>
</table>
