<?php
/* @var Phwoolcon\View\Engine\Php $this */
?>
<table class="w640 top-bar" cellpadding="0" cellspacing="0" border="0" bgcolor="#fff" width="100%">
    <tbody>
    <tr>
        <td class="w15" width="15"></td>
        <td valign="middle" align="left">
            <h1 class="header-content" style="font-size:30px;font-weight:normal;margin:10px 0;">
                <span style="color:#555;"><?= __('Phwoolcon') ?></span>
            </h1>
        </td>
        <td class="w15" width="15"></td>
    </tr>
    <tr>
        <td></td>
        <td style="border-bottom:1px solid #ddd;"></td>
        <td></td>
    </tr>
    </tbody>
</table>
